export const interiors = [
  { id: 1, name: "SVG Animation + mouse follow" },
  { id: 2, name: "CSS Animation + mouse follow" },
  { id: 3, name: "Three.js Animation + mouse follow" },
  { id: 4, name: "GSAP Animation + mouse follow" },
  { id: 5, name: "Canvas Animation + mouse follow" },
  { id: 6, name: "WebGL Animation + mouse follow" },
  { id: 7, name: "Particles.js Animation + mouse follow" },
  { id: 8, name: "Lottie Animation + mouse follow" },
  { id: 9, name: "Anime.js Animation + mouse follow" },
  { id: 10, name: "Velocity.js Animation + mouse follow" },
  { id: 11, name: "Tween.js Animation + mouse follow" },
  { id: 12, name: "React Spring Animation + mouse follow" },
  { id: 13, name: "Framer Motion Animation + mouse follow" },
  { id: 14, name: "React Transition Group Animation + mouse follow" },
  { id: 15, name: "Animate.css Animation + mouse follow" },
  { id: 16, name: "GreenSock Animation + mouse follow" },
  { id: 17, name: "Mo.js Animation + mouse follow" },
  { id: 18, name: "Popmotion Animation + mouse follow" },
  { id: 19, name: "ScrollMagic Animation + mouse follow" },
  { id: 20, name: "ScrollReveal Animation + mouse follow" },
  { id: 21, name: "Simple Animate Animation + mouse follow" },
  { id: 22, name: "WOW.js Animation + mouse follow" },
  { id: 23, name: "Waypoints Animation + mouse follow" },
  { id: 24, name: "Intersection Observer Animation + mouse follow" },
  { id: 25, name: "Smooth Scroll Animation + mouse follow" },
  { id: 26, name: "Parallax Animation + mouse follow" },
  { id: 27, name: "Scrollorama Animation + mouse follow" },
  { id: 28, name: "FullPage.js Animation + mouse follow" },
  { id: 29, name: "Swiper Animation + mouse follow" },
  { id: 30, name: "Slick Animation + mouse follow" },
  { id: 31, name: "Owl Carousel Animation + mouse follow" },
  { id: 32, name: "LightGallery Animation + mouse follow" },
  { id: 33, name: "Magnific Popup Animation + mouse follow" },
  { id: 34, name: "Fancybox Animation + mouse follow" },
  { id: 35, name: "PhotoSwipe Animation + mouse follow" },
  { id: 36, name: "Galleria Animation + mouse follow" },
  { id: 37, name: "Colorbox Animation + mouse follow" },
  { id: 38, name: "prettyPhoto Animation + mouse follow" },
  { id: 39, name: "justifiedGallery Animation + mouse follow" },
  { id: 40, name: "Isotope Animation + mouse follow" },
  { id: 41, name: "Masonry Animation + mouse follow" },
  { id: 42, name: "Packery Animation + mouse follow" },
  { id: 43, name: "Flickity Animation + mouse follow" },
  { id: 44, name: "Swiper Animation + mouse follow" },
  { id: 45, name: "Splide Animation + mouse follow" },
  { id: 46, name: "tns Animation + mouse follow" },
  { id: 47, name: "Swiper Animation + mouse follow" },
  { id: 48, name: "Flickity Animation + mouse follow" },
  { id: 49, name: "Isotope Animation + mouse follow" },
  { id: 50, name: "Splide Animation + mouse follow" },
  { id: 51, name: "Isotope Animation + mouse follow" },
  { id: 52, name: "Masonry Animation + mouse follow" },
  { id: 53, name: "Packery Animation + mouse follow" },
  { id: 54, name: "Flickity Animation + mouse follow" },
  { id: 55, name: "Swiper Animation + mouse follow" },
  { id: 56, name: "Splide Animation + mouse follow" },
  { id: 57, name: "tns Animation + mouse follow" },
  { id: 58, name: "Swiper Animation + mouse follow" },
  { id: 59, name: "Flickity Animation + mouse follow" },
  { id: 60, name: "Isotope Animation + mouse follow" },
];
